sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: TF8Nr5uHa2+GYlAQCkDG1B20Y2E1Rsuskz1FAMV195ftlW/fb1USnUJEwn/8cEK9LQIenWK26zhnUA7KfUt+rho5vtiCwrPuxqZqWRLbFo0urrc9d49Z0u49nIFpHSDI0rhCXYfFrJKNxRyBFloryHfksBItUa7sO2zrpzyD6sAfyxz7jsopVQhG1/9nUg8ZnF2qVrBibQe4ajd1QCZc7M1DJY6rTdxSfsaeOUrrs4SYw1nfNfE3lhJLj+F3ITL1rw1syn1iurLZZuKOZdIaj9XeCgc2qp+WyzxtnoLsYRJ2A4KQBI/gwtb12Ah1kdtXwCCrzZM4p/pQkvcs7qxP3YK9WWVhFWdbvF19Pr79UyFogiPmgrVajW3coelh/l+7+Fu16NDHqdYOUBkiMOnhvBfmrMB89fOcf6w1nec4MvZBHcsBf5A4IZHMoGnECNRqEMwxrus4n6rZIEt2edYEI6cvDwmn/vED/wU6lmMNxW4QlTdL64x9YZGa2naf+VL7bnrDDAV+wOP6Lv/IuFVfJZq1Yho+8B6EAaZdd48Fd79TTIuiblO1iXWXjhdYK9biR6mJrrZ+6vnG+YwfWuLOg5oMvHxCMZcF5HOo3CgImmcbHX8e+UFFBWN3MG6D8RwpxFcexwFa12Aita+UKyiZ6gaodfZBHhWbQ+Jg1K1KbEk=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: sdmGdBI3lIUEFnUxwKieKHZtJDr7YtFeEZPcPA9L0JHPQaO38V2Dt8SnyB9Xmh2xTanrB9yLobs4BOlhscWno69vs3FagSfDIkFmpjfYMYKj2/MpaySEdBkrRL2VnimgjStNtb0X7J0YbKuRUIbpLENfH3TRtUS2cPPTrRkBwTGqSO8MUGBWdjlo802VtI2+8TWPTt8tB6Rgc7NsoIu+JWSBKj/5WfUnsm//7y1cBGZwSptGDJnuaBSKaX68EItuPhhuHLMi4/9F6/7BTKxJDUdnAW29B4moQpBFytrJm0Z0YsBhrIfLHehc6MvahbliCipNTIvIBykHSwoRh+doV1GgvL5ItvGVHv1kDQc85AhaoBKdlpNwcpvwq/rhMFAXv1uvusgj7zMEeZaxZekkrcSPavtYch8VE92WhFFLH1iNsK90Li4nFfHlEq1gw3Z1zyCr6OZqMN7xOYTPrUQ6Ulih4DaIZjlOETBz3+xIs+jC46l5cXRJoNM0pnTb2yLaCoZDCcpAO8gzAzhusZ6NI8agfL3v3z1Lbnh7vW5ihXuixvhD4CMGI9gTd9ziuA11wSAO0c1vgn2Bi2b46S1t394TF87XSGdCOBJ/dHOql7NE5cLn8wjiUgk8gmozLMWLV0ngJa1/4F+GRVt5+TDQmxJxOx0danPPLdeXtBwQMjQ=
